# Basics

In [1]:
import numpy as np

In [2]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros([5,4]) 
np.ones((5,3))*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [5]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(5) # równomiernie rozmieszczone
np.random.randn(5) # rozmieszczone wg krzywej dzwonowej
rarr = np.random.randint(5,50,10)
print (rarr)

[13 29 24 24 10 49 38 17  8 40]


In [15]:
rarr.reshape((2,5))

array([[13, 29, 24, 24, 10],
       [49, 38, 17,  8, 40]])

In [16]:
rarr.max()
rarr.min()
rarr.argmax()
rarr.argmin()

8

# Indexing

In [17]:
arr = np.arange(0,21,2)

In [20]:
print(arr[5])
print(arr[2:5])
print(arr[5:])


10
[4 6 8]
[10 12 14 16 18 20]


In [21]:
slice = arr[0:5]

In [22]:
slice[:] = 99

In [23]:
slice

array([99, 99, 99, 99, 99])

In [24]:
arr #nadpisywanie wartości, gdyż numpy oszczędza pamięć

array([99, 99, 99, 99, 99, 10, 12, 14, 16, 18, 20])

In [25]:
arr_copy = arr.copy() #wykonanie kopii, by nie nadpisywać wartości

In [28]:
arr_2d =np.arange(5,50,5).reshape(3,3)
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [36]:
print(arr_2d[0])
print(arr_2d[:,0])
print(arr_2d[:2,1:])

[ 5 10 15]
[ 5 20 35]
[[10 15]
 [25 30]]


In [39]:
print(arr_2d)
print(arr_2d >20)
print(arr_2d[arr_2d >20])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[False False False]
 [False  True  True]
 [ True  True  True]]
[25 30 35 40 45]


In [41]:
ar2 = np.arange(50).reshape(5,10)
ar2[1:4,5:8]

array([[15, 16, 17],
       [25, 26, 27],
       [35, 36, 37]])

# Operations on arrays

In [42]:
arr = np.arange(11)

In [47]:
print(arr)
print(arr + arr)
print(arr * arr)
print(arr **3)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[  0   1   4   9  16  25  36  49  64  81 100]
[   0    1    8   27   64  125  216  343  512  729 1000]


In [51]:
print(np.sqrt(arr))
print(np.sin(arr))
print(np.argmax(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
10
